# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : Jekyll Bootstrap
tagline: Site Tagline
author :
  name : Name Lastname
  email : blah@email.test
  github : username
  twitter : username
  feedburner : feedname

name: Your New Jekyll Site
markdown: redcarpet
pygments: true

source: .
destination: ./_site
plugins: ./_plugins
layouts: ./_layouts

production_url : whoux.pro 
